# Generated by Django 6.1.1 on 2026-09-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.FileField(blank=True, upload_to='restaurant_photos/'),
        ),
    ]
