# Generated by Django 6.1.1 on 2026-09-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_item_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='delivery.customer')),
                ('items', models.ManyToManyField(related_name='orders', to='delivery.item')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
