# Generated by Django 6.1.1 on 2026-09-26 06:39

import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_lines(apps, schema_editor):
    Cart = apps.get_model('delivery', 'Cart')
    CartItem = apps.get_model('delivery', 'CartItem')
    Order = apps.get_model('delivery', 'Order')
    OrderItem = apps.get_model('delivery', 'OrderItem')

    old_cart_items = Cart._meta.get_field('items').remote_field.through
    old_order_items = Order._meta.get_field('items').remote_field.through
    CartItem.objects.bulk_create(
        [CartItem(cart_id=row.cart_id, item_id=row.item_id) for row in old_cart_items.objects.all()],
        ignore_conflicts=True,
    )
    OrderItem.objects.bulk_create(
        [OrderItem(order_id=row.order_id, item_id=row.item_id) for row in old_order_items.objects.all()],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='delivery.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_lines', to='delivery.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='delivery.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='delivery.order')),
            ],
        ),
        migrations.RunPython(preserve_existing_lines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', through='delivery.CartItem', to='delivery.item'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='delivery.OrderItem', to='delivery.item'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'item'), name='unique_item_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='unique_item_per_order'),
        ),
    ]
